name: wf-ci-develop

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize

jobs:
  linting-develop-job:
    name: Lint HTML and CSS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install 

      - name: Lint HTML Files With HTMLHint
        run: npx htmlhint "src/**/*.html"

      - name: Lint CSS Files With Stylelint
        run: npx stylelint "**/*.css"

  build-develop-job:
    name: Build With Parcel
    runs-on: ubuntu-latest
    needs: linting-develop-job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Test Build With Parcel
        run: npx parcel build "./src/index.html" --dist-dir "./dist" --public-url "./"